module.exports =
  DEFAULT_LANGUAGE: 'en'
  DELIM_MULTI_VALUE: ';'
  DELIM_HEADER_LANGUAGE: '.'
  DELIM_CATEGORY_CHILD: '>'
  DELIM_TIERS_MULTI_VALUE: '%'
  DELIM_URL_ATTRIBUTES_SEPERATOR: '|'
  DELIM_DIMENSIONS_SEPERATOR: 'x'

